"""
Evaluate sentiment model on the test set and register it
in the MLflow Model Registry.

Run:
    python scripts/evaluate.py
"""

import os
import sys
import mlflow
import mlflow.transformers
import pandas as pd
from dotenv import load_dotenv
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# Add the parent directory (starter/) to the Python path so it can find 'app'
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from app.utils import load_classifier

# 1. Load environment variables from your .env file
load_dotenv()
tracking_uri = os.getenv("MLFLOW_TRACKING_URI", "http://localhost:5000")
experiment_name = os.getenv("MLFLOW_EXPERIMENT_NAME", "FinBERT_Sentiment_Analysis")
model_name = os.getenv("MODEL_NAME", "FinBERT_Model")

# 2. Set MLflow Tracking URI and Experiment
mlflow.set_tracking_uri(tracking_uri)
mlflow.set_experiment(experiment_name)

def evaluate():
    # 3. Load your test data generated by DVC
    test_df = pd.read_csv("data/test.csv")
    
    # 4. Load the FinBERT model
    os.environ["MODEL_SOURCE"] = "huggingface"
    model_pipeline = load_classifier()
    
    with mlflow.start_run() as run:
        # Log a model parameter
        mlflow.log_param("model_type", "FinBERT")
        mlflow.log_param("dataset_size", len(test_df))
        
        # 5. Generate predictions
        # (Adapt this loop/apply based on how your model_pipeline expects input)
        y_true = test_df['label'].tolist()
        texts = test_df['text'].tolist()
        
        print("Running predictions...")
        # Assuming the pipeline returns a list of dicts like [{'label': 'positive', 'score': 0.9}]
        predictions = model_pipeline(texts)
        y_pred = [pred['label'] for pred in predictions]
        
        # 6. Compute metrics
        accuracy = accuracy_score(y_true, y_pred)
        f1 = f1_score(y_true, y_pred, average='weighted')
        precision = precision_score(y_true, y_pred, average='weighted', zero_division=0)
        recall = recall_score(y_true, y_pred, average='weighted', zero_division=0)
        
        # Log metrics
        mlflow.log_metrics({
            "accuracy": accuracy,
            "f1_weighted": f1,
            "precision_weighted": precision,
            "recall_weighted": recall
        })
        
        print(f"Metrics: F1={f1:.4f}, Accuracy={accuracy:.4f}")
        
        # 7. Log and Register the model        
        # Log the model to MLflow artifacts
        model_info = mlflow.transformers.log_model(
            transformers_model=model_pipeline,
            artifact_path="model",
            task="text-classification"
        )
        
        # Register the model in the Model Registry
        mlflow.register_model(
            model_uri=model_info.model_uri,
            name=model_name
        )
        print(f"Model registered as: {model_name}")

if __name__ == "__main__":
    evaluate()